print("Enter your first num")
n1=input()
print("Enter your second num")
n2=input()
print("sum",int(n1)+int(n2))
print("subs",int(n1)-int(n2))
print("multi",int(n1)*int(n2))
print("div",int(n1)/int(n2))
print("module",int(n1)%int(n2))
